Many security updates
HackGT/ground-truth pull request #37
Opened 2020-12-27 20:58 UTC by ayush-goyal

- Add 404 and 500 error pages rather than stack traces in prod
<img width="1413" alt="Screen Shot 2020-12-27 at 3 45 39 PM" src="https://user-images.githubusercontent.com/8273038/103179539-34345200-485b-11eb-9bb6-3e9fbc653ff0.png">
<img width="1275" alt="Screen Shot 2020-12-27 at 3 47 06 PM" src="https://user-images.githubusercontent.com/8273038/103179540-35657f00-485b-11eb-850c-91b9cb5de55e.png">

-----

- Add password complexity/length requirement
- At first, I only added password checking when signing up, but in a later commit I added it in when changing/resetting your password
<img width="1338" alt="Screen Shot 2020-12-27 at 3 46 09 PM" src="https://user-images.githubusercontent.com/8273038/103179548-457d5e80-485b-11eb-9559-90d1e321d475.png">

-----

- Update all dependencies to latest - some of them add security updates that were needed
- I had to add in new typings and updated the mongo db options because of this

-----

- Switched bugsnag error handling over to sentry since this is what we will be using going forward

-----

- Added CSRF protection for all forms (ex. when changing password, and for all admin endpoints)
- Added in express Helmet for protection
- Refactored express post parser

-----

- Added rate limiting to all endpoints, and created utility functions for different rate limiting options per endpont (in middleware.ts)

2020-12-27 22:12 UTC, ehsanmasdar commented
This is awesome!

> Added rate limiting to all endpoints, and created utility functions for different rate limiting options per endpont (in middleware.ts)
Might be worth adding recaptcha on some endpoints to reduce risk of brute force/spam even further.

2020-12-27 22:19 UTC, evan10s commented
Same as Ehsan, these are all excellent improvements to make!  I will look at the code shortly - I agree about recaptcha and have a couple thoughts about password complexity requirements as well

2020-12-28 05:04 UTC, ayush-goyal commented
@ehsanmasdar @evan10s I added in recaptcha for certain routes. See [login.dev.hack.gt](login.dev.hack.gt)
<img width="1392" alt="Screen Shot 2020-12-28 at 12 03 46 AM" src="https://user-images.githubusercontent.com/8273038/103190740-41bffb00-48a0-11eb-8906-927665de5ebe.png">

2020-12-29 20:04 UTC, evan10s requested changes

2020-12-29 20:05 UTC, evan10s commented on src/auth/strategies/Local.ts
> +passwordSchema
I also lose all the data I entered if I try to submit without completing recaptcha.

2020-12-29 20:05 UTC, evan10s commented
Also, when I sign in at login.dev.hack.gt, I get taken to https://login.dev.hack.gt/favicon.ico instead of the 404 page.

2020-12-29 20:26 UTC, ayush-goyal commented
> Also, when I sign in at login.dev.hack.gt, I get taken to https://login.dev.hack.gt/favicon.ico instead of the profile page.
Can you explain more? When I sign in I go to the profile page

2020-12-29 21:39 UTC, evan10s commented
As crazy as this sounds, it only seems to happen if I click on the icon part of the Next button or if I complete the recaptcha, then click back to the password field and hit Enter (in Chrome on Windows).  It still ends up logging me in though, and both of those seem to be consistent causes

2020-12-29 21:46 UTC, ayush-goyal commented
I'm not sure what the problem is and I can't replicate it. Can you try a hard reload and clear your cache?

2020-12-29 23:27 UTC, evan10s commented
Yeah, it's still happening in an incognito window.

2020-12-30 02:48 UTC, evan10s approved these changes

2020-12-30 02:52 UTC, merged